### ISSUE TITLE
想问下iOS10可以支持吗，编译不过，float3x3这个函数不存在

### ISSUE THREAD

**Issue by miliPolo** [alexiscn/MetalFilters#1]
Filters/MTValenciaFilter.metal:23: no matching constructor for initialization of 'metal::float3x3' (aka 'matrix<float, 3, 3>')
我想问下有替代float3x3的函数吗，我想在iOS10下面跑

**Comment by alexiscn** [comment]
according Metal wiki [https://en.wikipedia.org/wiki/Metal_(API)](https://en.wikipedia.org/wiki/Metal_(API))

> On June 5, 2017 at WWDC, Apple announced the second version of Metal, to be supported by macOS High Sierra, iOS 11 and tvOS 11. 

So the answer is no.
