### ISSUE TITLE
Add more custom filters

### ISSUE THREAD

**Issue by chintanMaisuriya** [alexiscn/MetalFilters#3]
Hi there,
I'm working on an application in which I've to add the image filter functionality with filters like instagram and I found MetalFilters is the perfect for me. Only one thing that bother me is that "How to add more custom filters (i.e. how to create custom filter files to add more custom filters)?"
Please help me with this.

Thank You.

**Comment by alexiscn** [comment]
You can have a look at `MTFilter ` which is the super class of all filters. You can create a class inherit `MTFilter` and override those properties.
