### ISSUE TITLE
Crash since iOS 13.3.1

### ISSUE THREAD

**Issue by mariusvirus** [alexiscn/MetalFilters#4]
This issue happens on the Demo app because some resources cannot be loaded.

Crashed here "Fatal error: Unexpectedly found nil while unwrapping an Optional value"
<img width="676" alt="crash" src="https://user-images.githubusercontent.com/6607861/74661326-65a2b280-51a0-11ea-896d-2402598ef8da.png">

I just found out that the problem is somewhere in metal file, for example "MTHudsonFragment" in MTHudsonFilter.metal. I do not know what the problem is exactly. Thank you!

**Comment by alexiscn** [comment]
It seems that we can not init `CIImage` with PVR format texture in iOS 13.3.1.

I have change to load texture with `MTLTextureLoader` and seems to fixed that crash.

**Comment by mariusvirus** [comment]
Everything look fine now and it is working as is should. Thank you and can you please guide me to some tutorial of kernel or how can I make my own custom filters?
