### ISSUE TITLE
可以分享一下这些instagram filter的参数是在哪里获取的么？

### ISSUE THREAD

**Issue by Haibo-Zhou** [alexiscn/MetalFilters#5]
很棒的项目，我对比了instagram photo filter。完全一致！

可以请教一下filter的参数是如何获得的么，最近我在研究Core Image，想尝试一下能不能写出和INS一样的filter效果，不过一致找不到INS filter的参数设置。

**Comment by alexiscn** [comment]
Those filters dumps from Instagram App. So the effect should be equal to instagram.

**Comment by Haibo-Zhou** [comment]
Thx for the quick reply. Could you tell me how to dumps the filters from instagram? Does INS provide some way to fetch them?

**Comment by alexiscn** [comment]
1. Download a decrypted instagram ipa
2. Debug instagram with MonkeyDev
3. Dump all OpenGL shaders with MonkeyDev hook script
4. convert those shaders to Metal

That's all

**Comment by Haibo-Zhou** [comment]
Got it. Thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: alexiscn <notifications@github.com>
发送时间: Wednesday, June 3, 2020 5:55:05 PM
收件人: alexiscn/MetalFilters <MetalFilters@noreply.github.com>
抄送: Haibo-Zhou <chuckzhb@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [alexiscn/MetalFilters] 可以分享一下这些instagram filter的参数是在哪里获取的么？ (#5)


  1.  Download a decrypt instagram ipa
  2.  Debug instagram with MonkeyDev
  3.  Dump all OpenGL shaders with MonkeyDev hook script
  4.  covert those shaders to Metal

That's all

―
