### ISSUE TITLE
Input Texyures for Lux filter

### ISSUE THREAD

**Issue by sahaand** [alexiscn/MetalFilters#7]
Hi Alex,
I'm very thankful for your very useful Repo
Actually, I'm an Android developer, and I've been developing an Instagram like app but I couldn't find All Instagram filters while I've seen your fantastic Repo. In fact, I've been using GLSL, so I convert your metal code but I couldn't find Input Textures that you have used in the Lux program.

Would you please help me?
and did you now GLSL? I'm wondering how did you write all the Instagram filters.

**Comment by alexiscn** [comment]
Those filters all came from Instagram GLSL. I converted them to Metal. 
Which filter do you want to get the GLSL?

**Comment by sahaand** [comment]
Yes, I see.
I want to use lux and structure filter, but I couldn't find complete usage in your code. unfortunately, I couldn't get GLSL Shaders code from decompiled APK. If you have it would you please put them in your repo as raw or send them to me ?

**Comment by alexiscn** [comment]
Oh, LUX and Structure filters not implemented yet. All shaders code can be found in [here](https://gist.github.com/alexiscn/53d93aae95023293e5017e152f871b68).

**Comment by sahaand** [comment]
I'm very thankful :))
